-- Optional Supabase table for de-identified storage
create table if not exists plans (
  id bigint generated by default as identity primary key,
  reference text unique,
  created_at timestamp with time zone default now(),
  inputs_json jsonb not null,
  output_json jsonb not null
);
